version: '2'
services:
    zsoft-app:
        image: zsoft
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://zsoft-mariadb:3306/zsoft
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://zsoft-elasticsearch:9200
        ports:
            - 8080:8080
    zsoft-mariadb:
        extends:
            file: mariadb.yml
            service: zsoft-mariadb
    zsoft-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: zsoft-elasticsearch
